In [34]:
import numpy as np
import pandas as pd

In [35]:
print("creating a dataframe")

creating a dataframe

In [36]:
data={
    'Name':['john','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
data_list=[
    ['john',28,'New york',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000],
]
df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0   john  28  New york  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [38]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
print("selection and indexing of column")

selection and indexing of column

In [40]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [41]:
df2[['City','Name']]

       City   Name
0  New York   John
1     Paris   Anna
2    Berlin  Peter
3    London  Linda

In [42]:
print('creating a column')

creating a column

In [43]:
df2["designation"]=["doctor","enginner","actor","vlogger"]

In [44]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    enginner
2  Peter   29    Berlin   62000       actor
3  Linda   42    London   85000     vlogger

In [45]:
print("remove column")

remove column

In [48]:
df2.drop(["designation", "Salary"], axis=1)   #inplace true used for actualy deleting from dataframe

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   42    London

In [47]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    enginner
2  Peter   29    Berlin   62000       actor
3  Linda   42    London   85000     vlogger

In [49]:
df2.drop(0,axis=0)

    Name  Age    City  Salary designation
1   Anna   34   Paris   70000    enginner
2  Peter   29  Berlin   62000       actor
3  Linda   42  London   85000     vlogger

In [50]:
print("selecting rows")

selecting rows

In [53]:
df2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
designation      doctor
Name: 0, dtype: object

In [54]:
df2.loc[[0,1]]

   Name  Age      City  Salary designation
0  John   28  New York   65000      doctor
1  Anna   34     Paris   70000    enginner

In [55]:
df2.iloc[3]  #index location baat wahi hai par index kuch bhi ho skta hai

Name             Linda
Age                 42
City            London
Salary           85000
designation    vlogger
Name: 3, dtype: object

In [56]:
print("selecting subsets of rows and columns")

selecting subsets of rows and columns

In [58]:
df.loc[[0,1]][["Name","Age"]]

   Name  Age
0  john   28
1  Anna   34

In [59]:
df.loc[[2,1]][["City","Salary"]]

     City  Salary
2  Berlin   62000
1   Paris   70000

In [60]:
print("conditional selection")

conditional selection

In [61]:
#i only want to see whose age is greater than 30

In [62]:
df2[df2["Age"]>30]

    Name  Age    City  Salary designation
1   Anna   34   Paris   70000    enginner
3  Linda   42  London   85000     vlogger

In [63]:
#i only want to see whose age is greater than 30 and there city must be paris

In [65]:
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary designation
1  Anna   34  Paris   70000    enginner

missing data